### 应用通用设置
spring:
  profiles:
    active: dev

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

server:
  port: 8080
  servlet:
    context-path: /jsp

application:
  message: Hello Grady!
---


### 开发环境配置
spring:
  profiles: dev

---


### 生产环境配置
spring:
  profiles: pro
