### 应用通用设置
spring:
  profiles:
    active: dev

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

  redis:
    host: localhost 
    port: 6379
    password:
    database: 0
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8

server:
  port: 8080
  servlet:
    context-path: /jsp

---


### 开发环境配置
spring:
  profiles: dev

---


### 生产环境配置
spring:
  profiles: pro
